package de.nxthg.greifer;

public enum GreiferEvents {
	STARTEN_AUFLADEN,KISTE_GROSS_OBEN,KISTE_MITTEL_UNTEN,KISTE_MITTEL_MITTE,KISTE_KLEIN_UNTEN, GANZAUF, AUF_KISTENHOEHE_EINZIEHEN,AUF_CARGOAREA_EINZIEHEN,
	STARTEN_ABLADEN,AUF_CARGOAREA_AUSWERFEN, AUF_BODEN_AUSWERFEN, STOP,
	AUF_KISTENHOEHE_FAHREN_UNTEN, AUF_KISTENHOEHE_FAHREN_MITTE, AUF_KISTENHOEHE_FAHREN_OBEN, 
	AUF_CARGOAREA_FAHREN, AUF_BODEN_FAHREN, KISTE_IST_DRAUF
}
