package de.nxthg.greifer;

public enum GreiferEvents {
	STARTEN_AUFLADEN,KISTE_GROSS,KISTE_MITTEL, GANZAUF, AUF_KISTENHOEHE_EINZIEHEN,AUF_ARGOAREA_EINZIEHEN,
	STARTEN_ABLADEN,AUF_CARGOAREA_AUSWERFEN, AUF_BODEN_AUSWERFEN, 
}
