package de.nxthg.greifer;

public enum GreiferEvents {
	STARTEN_AUFLADEN,KISTE_GROSS_OBEN,KISTE_MITTEL_UNTEN,KISTE_MITTEL_MITTE,KISTE_KLEIN_UNTEN, GANZAUF, AUF_KISTENHOEHE,AUF_CARGOAREA,
	STARTEN_ABLADEN,AUF_CARGOAREA_AUSWERFEN, AUF_BODEN_AUSWERFEN, STOP,
	AUF_KISTENHOEHE_FAHREN_UNTEN, AUF_KISTENHOEHE_FAHREN_MITTE, AUF_KISTENHOEHE_FAHREN_OBEN, 
	AUF_CARGOAREA_FAHREN, AUF_BODEN_FAHREN, KISTE_IST_DRAUF, FAHR_ZURUECK, FAHR_VOR,FAHRER_VORNE,FAHRER_HINTEN,CARGOAREA_REIN,ABLADEN, EINZIEHEN, 
	STOP_EINZIEHEN, FAHR_ZURUECK_5CM, FAHRER_HINTEN_5CM, FAHR_VOR_5CM, FAHRER_VORNE_5CM, ZUM_EINSAUGEN_RUNTER, AUF_EINSAUG_HOEHE
}
