package de.nxthg.fahrer;


public enum GreiferEvents {
	KISTE_GROSS_OBEN,KISTE_MITTEL_UNTEN,KISTE_MITTEL_MITTE,KISTE_KLEIN_UNTEN, AUF_KISTENHOEHE,AUF_CARGOAREA,
	AUF_CARGOAREA_FAHREN,FAHR_ZURUECK, FAHR_VOR,FAHRER_VORNE,FAHRER_HINTEN,CARGOAREA_REIN,ABLADEN
}
